# Training with 130 data samples

In [1]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, accuracy_score

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

print(type(iris))
print("iris.data :", iris.data.shape)
print("iris.target :", iris.target.shape)

# Fix the seed and stratify to ensure same output every time
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=130, test_size=20, random_state=42, stratify=y
)

print("X_train :", type(X_train), X_train.shape)
print("X_test :", type(X_test), X_test.shape)
print("y_train :", type(y_train), y_train.shape)
print("y_test :", type(y_test), y_test.shape)

# Train Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

print("\n True class :", y_test)
print("\n Predicted class : ", y_pred)

# Evaluate
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Precision Score: ", precision_score(y_test, y_pred, average= None))
print("Recall Score: ", recall_score(y_test, y_pred, average= None))
print("F1 Score: ", f1_score(y_test, y_pred, average= None))

<class 'sklearn.utils._bunch.Bunch'>
iris.data : (150, 4)
iris.target : (150,)
X_train : <class 'numpy.ndarray'> (130, 4)
X_test : <class 'numpy.ndarray'> (20, 4)
y_train : <class 'numpy.ndarray'> (130,)
y_test : <class 'numpy.ndarray'> (20,)

 True class : [1 2 1 2 1 2 0 0 2 1 1 0 2 2 0 0 1 2 1 0]

 Predicted class :  [1 2 1 2 1 2 0 0 2 1 1 0 2 2 0 0 1 2 2 0]
Confusion Matrix:
 [[6 0 0]
 [0 6 1]
 [0 0 7]]
Accuracy Score:  0.95
Precision Score:  [1.    1.    0.875]
Recall Score:  [1.         0.85714286 1.        ]
F1 Score:  [1.         0.92307692 0.93333333]
